export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const ADD_PODCAST = "ADD_PODCAST";
export const ADD_EPISODE = "ADD_EPISODE";
